- title: "Volunteer, WiCSCon 2025"
  organization: "Women in Computing (WiCS), Ashoka University"
  description: "Handled logistics and helped organize WiCSCon 2025, WiCS's flagship conference focused on gender and society in tech."
- title: "Peer Mentor, CS Society"
  organization: "CS Society, Ashoka University"
  description: "Mentored first and second year CS students, helping them navigate their academics and other opporunities in CS."  