- title: "Program Committee, ML4Science Workshop"
  organization: "NeurIPS 2024"
  description: "Reviewed 10 submissions, provided constructive feedback, and participated in meta-reviews."
- title: "Reviewer"
  organization: "Journal of Machine Learning Research (JMLR)"
  description: "Reviewed invited manuscript on representation learning and fairness."